version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: hydrogen-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: hydrogen-credits
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - hydrogen-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hydrogen-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/hydrogen-credits?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-here-change-this-in-production
      - BLOCKCHAIN_NETWORK=localhost
      - BLOCKCHAIN_RPC_URL=http://blockchain:8545
      - BLOCKCHAIN_PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS:-0x0000000000000000000000000000000000000000}
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongodb
      - blockchain
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - hydrogen-network

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hydrogen-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_BLOCKCHAIN_NETWORK=localhost
      - REACT_APP_CONTRACT_ADDRESS=${CONTRACT_ADDRESS:-0x0000000000000000000000000000000000000000}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - hydrogen-network

  # Local Blockchain Node (Hardhat)
  blockchain:
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    container_name: hydrogen-blockchain
    restart: unless-stopped
    ports:
      - "8545:8545"
    environment:
      - HARDHAT_NETWORK=localhost
    volumes:
      - ./blockchain:/app
      - blockchain_data:/app/data
    networks:
      - hydrogen-network
    command: npx hardhat node --hostname 0.0.0.0

  # Blockchain Deployer (runs once to deploy contracts)
  deployer:
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    container_name: hydrogen-deployer
    depends_on:
      - blockchain
    environment:
      - HARDHAT_NETWORK=localhost
    volumes:
      - ./blockchain:/app
    networks:
      - hydrogen-network
    command: >
      sh -c "
        echo 'Waiting for blockchain node to start...' &&
        sleep 10 &&
        echo 'Deploying contracts...' &&
        npx hardhat run scripts/deploy.js --network localhost &&
        echo 'Contracts deployed successfully!'
      "

volumes:
  mongodb_data:
    driver: local
  blockchain_data:
    driver: local

networks:
  hydrogen-network:
    driver: bridge
